### ISSUE TITLE
navigator.geolocation 의 성능 상의 문제를 해결한다.

### ISSUE THREAD

**Issue by YejiAhn** [woowacourse-teams/2020-doran-doran#15]
## 목적
종종 사용자의 위치를 받아오지 못하거나, 사용자 위치의 정확성이 떨어지는 문제를 해결한다.

## 상세 작업내용
- [ ] geolocation 옵션 중 timeOut 옵션을 설정한다.

**Comment by hwookim** [comment]
https 적용으로 해결
