### ISSUE TITLE
글 새로고침 기능을 수정한다.

### ISSUE THREAD

**Issue by YejiAhn** [woowacourse-teams/2020-doran-doran#172]
## 목적
새로고침 기능이 작동하지 않는 이슈를 해결한다.

## 상세 작업내용
- [x] endDate 오버라이드한다.

## 주의사항
#173 에서 로직 변경이 이뤄진 점 참고할 것

**Comment by hwookim** [comment]
#173의 로직 변경 중 해결되었습니다.
