### ISSUE TITLE
배포 자동화를 구성한다.

### ISSUE THREAD

**Issue by LTTTTTE** [woowacourse-teams/2020-doran-doran#35]
## 목적

특정 branch에 push가 될경우 배포, 서비스가 자동화 되도록 한다.

## 상세 작업내용
- [x]  jenkins로 빌드, 배포, 서비스 실행하도록 한다.
- [x]  secret file이 빌드 과정에서 주입되도록 한다.

**Comment by YebinK** [comment]
* [HTTPS + NginX + SpringBoot](https://github.com/woowacourse-teams/2020-doran-doran/wiki/NginX,-SpringBoot-%EC%97%90-Https-%EB%B6%99%EC%9D%B4%EA%B8%B0)

* [EC2에 젠킨스 설치하기](https://github.com/woowacourse-teams/2020-doran-doran/wiki/EC2%EC%97%90-Jenkins-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)

* [젠킨스 Publish Over SSH와 Github Webhook 설정](https://github.com/woowacourse-teams/2020-doran-doran/wiki/%EC%A0%A0%ED%82%A8%EC%8A%A4-Publish-Over-SSH%EC%99%80-Github-Webhook-%EC%84%A4%EC%A0%95)
